name: Rainix CI
on: [push]

jobs:
  standard-tests:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    env:
      RPC_URL_ARBITRUM: ${{ secrets. CI_DEPLOY_ARBITRUM_RPC_URL}}
      RPC_URL_ETH: ${{ secrets. RPC_URL_ETH}}
      CI_DEPLOY_SEPOLIA_RPC_URL: ${{ secrets.CI_DEPLOY_SEPOLIA_RPC_URL || vars.CI_DEPLOY_SEPOLIA_RPC_URL }}
      CI_FORK_SEPOLIA_BLOCK_NUMBER: ${{ vars.CI_FORK_SEPOLIA_BLOCK_NUMBER }}
      CI_FORK_SEPOLIA_DEPLOYER_ADDRESS: ${{ vars.CI_FORK_SEPOLIA_DEPLOYER_ADDRESS }}
      CI_SEPOLIA_METABOARD_URL: ${{ vars.CI_SEPOLIA_METABOARD_URL }}
      CI_DEPLOY_POLYGON_RPC_URL: ${{ secrets.CI_DEPLOY_POLYGON_RPC_URL }}
      RPC_URL_ETHEREUM_FORK: ${{ secrets.RPC_URL_ETHEREUM_FORK }}
      RPC_URL_FLARE: ${{ secrets. CI_DEPLOY_FLARE_RPC_URL }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix develop -c rainix-sol-prelude

      - run: ./prep-tauri.sh
        working-directory: lib/h20.test-std/lib/rain.orderbook

      - run: nix develop -c rainix-sol-test